import {
  AlignJustify,
  Check,
  ChevronDown,
  ChevronsUpDown,
  Edit2,
  EyeOff,
  Moon,
  MoreHorizontal,
  Plus,
  Search,
  SlidersHorizontal,
  SortAsc,
  SortDesc,
  SunMedium,
  Trash,
  Twitter,
  X,
} from 'lucide-react'

export const Icons = {
  sun: SunMedium,
  moon: Moon,
  twitter: Twitter,
  burgerMenu: AlignJustify,
  closeMenu: X,
  check: Check,
  edit: Edit2,
  sort: ChevronsUpDown,
  asc: SortAsc,
  desc: SortDesc,
  hide: EyeOff,
  dotsHorizontal: MoreHorizontal,
  trash: Trash,
  options: SlidersHorizontal,
  plus: Plus,
  search: Search,
  arrowDown: ChevronDown,
}
